DROP INDEX job_executions_job_status_started_idx ON job_executions;
DROP INDEX scheduled_jobs_scope_status_created_idx ON scheduled_jobs;
DROP INDEX scheduled_jobs_scope_upstream_created_idx ON scheduled_jobs;
DROP INDEX scheduled_jobs_scope_created_idx ON scheduled_jobs;

